// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	GetAllUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
